### ISSUE TITLE
UC08 - Message customer

### ISSUE THREAD

**Issue by itsywr** [Piyush-Bhor/CC_Capstone#2]
**Use Case:**	UC08 - Message customer
**Scenario:**	The customer wants to send a text message to a lender or renter regarding a specific item.
**Actor**	Customer
**Preconditions:**	The customer is currently logged in and has identified a lender or renter to contact.
**Post-Conditions:**	A new text channel is created between the customer and the lender/renter for communication.
**Related Use Case:**	None
**Stakeholders:**
* Customer (primary actor): Initiates the message request. 
* System: Creates a text channel for communication.

**Comment by Piyush-Bhor** [comment]
Feature added.
